---
- name: Check git diff and ls-files
  when: ensure_commit.check
  changed_when: gitdiff.stdout
  shell: |
    set -o pipefail
    {% if ensure_commit.gitdir is defined %} pushd {{ ensure_commit.gitdir }} > /dev/null
    {% endif %}
    git diff --name-status {{ ensure_commit.gitpaths }}
    git diff --name-status --staged {{ ensure_commit.gitpaths }}
    git ls-files --other --exclude-standard  {{ ensure_commit.gitpaths }} | xargs --no-run-if-empty -n1 echo -e "U\t"
    popd > /dev/null
  register: gitdiff
  check_mode: false

- name: Confirm committal of key and cert
  when: ensure_commit.check and not ansible_check_mode and gitdiff.stdout
  pause:
    prompt: "{{ gitdiff.stdout }}\n{{ ensure_commit.gitpromt | default('Make sure you have committed the listed files') }}"

- name: Fail if uncommited keys and certs
  when: ensure_commit.check and ensure_commit.fail and not ansible_check_mode
  shell: |
    set -o pipefail
    {% if ensure_commit.gitdir is defined %} pushd {{ ensure_commit.gitdir }} > /dev/null
    {% endif %}
    git diff --name-status {{ ensure_commit.gitpaths }}
    git diff --name-status --staged {{ ensure_commit.gitpaths }}
    git ls-files --other --exclude-standard  {{ ensure_commit.gitpaths }} | xargs --no-run-if-empty -n1 echo -e "U\t"
    popd > /dev/null
  register: gitdiff
  failed_when: gitdiff.stdout
