- name: Check git diff and ls-files
  changed_when: gitdiff.stdout
  shell: |
    set -o pipefail
    pushd {{ gitdir }} > /dev/null
    git {% if gitdir is defined %} {% endif %} diff --name-status {{ gitpaths }}
    git {% if gitdir is defined %} {% endif %} diff --name-status --staged {{ gitpaths }}
    git {% if gitdir is defined %} {% endif %} ls-files --other --exclude-standard  {{ gitpaths }} | xargs --no-run-if-empty -n1 echo -e "U\t"
    popd > /dev/null
  register: gitdiff
  check_mode: no

- name: Confirm committal of key and cert
  when: not ansible_check_mode and gitdiff.stdout
  pause:
    prompt: "{{ gitdiff.stdout }}\n{{ gitpromt | default('Make sure you have committed the listed files') }}"

- name: Fail if uncommited keys and certs
  when: not ansible_check_mode
  shell: |
    set -o pipefail
    pushd {{ gitdir }} > /dev/null
    git {% if gitdir is defined %} {% endif %} diff --name-status {{ gitpaths }}
    git {% if gitdir is defined %} {% endif %} diff --name-status --staged {{ gitpaths }}
    git {% if gitdir is defined %} {% endif %} ls-files --other --exclude-standard  {{ gitpaths }} | xargs --no-run-if-empty -n1 echo -e "U\t"
    popd > /dev/null
  register: gitdiff
  failed_when: gitdiff.stdout
