---
- name: Enroll certificates
  import_role:
    name: libellum_client
  tags:
    - libellum

- name: Set clavem_update
  set_fact:
    clavem_update: true
  tags:
    - never
    - update

- name: Install Clavem and pre-reqs
  package:
    name: [ clavem-server, python2-psycopg2 ]
    state: present
  when: clavem_update is not defined or not clavem_update
  notify:
    - restart clavem-server

- name: Update clavem and pre-reqs  # noqa 403 Skip rule for not using "state: latest" as this task's purpose is to update the package
  when: clavem_update is defined and clavem_update
  package:
    name: [ clavem-server, python2-psycopg2 ]
    state: latest
  notify:
    - restart clavem-server

- name: Set permissions on certificates
  import_role:
    name: libellum_certs
  tags:
    - libellum

- name: Copy clavem config
  template:
    src: etc/clavem.conf.d/20-config.yml.j2
    dest: /etc/clavem.conf.d/20-config.yml
    owner: root
    group: clavem-server
    mode: 0640
  notify:
    - restart clavem-server

- name: Create encryption certificate directories locally  # noqa 208
  run_once: true
  delegate_to: localhost
  become: false
  file:
    path: "{{ inventory_files_dir }}{{ item }}/clavem/"
    state: directory
  loop:
    - "{{ o24_libellum_certificates_base_path }}"
    - "{{ o24_libellum_keys_base_path }}"

- name: Set operator path
  set_fact:
    operator_tls_certificates_base_path: "{{ o24_libellum_certificates_base_path }}"
    operator_tls_keys_base_path: "{{ o24_libellum_keys_base_path }}"

- name: Create encryption certificate directories
  file:
    mode: 0755
    path: "{{ item }}/clavem/"
    state: directory
  loop:
    - "{{ o24_libellum_certificates_base_path }}"
    - "{{ o24_libellum_keys_base_path }}"

- name: migrate old certificates
  run_once: true
  when: tls_certificates_base_path != o24_libellum_certificates_base_path
  block:
    - name: Find old encryption certificates
      # when: not ansible_check_mode
      run_once: true
      find:
        paths: "{{ tls_certificates_base_path }}/clavem/"
      register: old_encryption_crts

    - name: Find old encryption keys
      # when: not ansible_check_mode
      run_once: true
      find:
        paths: "{{ tls_keys_base_path }}/clavem/"
      register: old_encryption_keys

    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: certs {{ old_encryption_crts.files | map(attribute='path') | map('basename') | list }} and keys {{ old_encryption_keys.files | map(attribute='path') | map('basename') | list }}

    - name: Migrate certificates from old location to new
      include_tasks: ../../libellum_client/tasks/move_and_link.yml
      vars:
        from_base_path: "{{ tls_certificates_base_path }}/clavem/"
        to_base_path: "{{ o24_libellum_certificates_base_path }}/clavem/"
      loop: "{{ old_encryption_crts.files | map(attribute='path') | map('basename') | list }}"

    - name: Migrate keys from old location to new
      include_tasks: ../../libellum_client/tasks/move_and_link.yml
      vars:
        from_base_path: "{{ tls_keys_base_path }}/clavem/"
        to_base_path: "{{ o24_libellum_keys_base_path }}/clavem/"
      loop: "{{ old_encryption_keys.files | map(attribute='path') | map('basename') | list }}"

- name: Copy encryption certificates
  when: not ansible_check_mode
  run_once: true
  copy:
    src: "{{ inventory_files_dir }}{{ o24_libellum_certificates_base_path }}/clavem/"
    dest: "{{ o24_libellum_certificates_base_path }}/clavem/"
    owner: root
    group: clavem-server
    mode: 0640
  notify:
    - restart clavem-server

- name: Copy encryption keys
  when: not ansible_check_mode
  run_once: true
  copy:
    src: "{{ inventory_files_dir }}{{ o24_libellum_keys_base_path }}/clavem/"
    dest: "{{ o24_libellum_keys_base_path }}/clavem/"
    owner: root
    group: clavem-server
    mode: 0640
  notify:
    - restart clavem-server

- name: Enroll Encryption Certificates
  include_role:
    name: libellum_client
    apply:
      run_once: true
    tasks_from: enroll
  vars:
    outscan_enroll_skip_install: true
    libellum:
      service: "ENCRYPTION"
      user: clavem-server
      cert: "encryption.crt"
      key: "encryption.key"
      passphrase: "{{ vault_clavem_encryption_key_passphrase }}"
    o24_libellum_certificates_base_path: "{{ operator_tls_certificates_base_path }}/clavem"
    o24_libellum_keys_base_path: "{{ operator_tls_keys_base_path }}/clavem"

- name: Find encryption certificates
  when: not ansible_check_mode
  run_once: true
  find:
    paths: "{{ o24_libellum_certificates_base_path }}/clavem/"
  register: encryption_crts

- name: Fetch encryption certificates
  when: not ansible_check_mode
  run_once: true
  loop: "{{ encryption_crts.files | map(attribute='path') | list }}"
  fetch:
    flat: true
    src: "{{ item }}"
    dest: "{{ inventory_files_dir }}{{ o24_libellum_certificates_base_path }}/clavem/"

- name: Find encryption keys
  when: not ansible_check_mode
  run_once: true
  find:
    paths: "{{ o24_libellum_keys_base_path }}/clavem/"
  register: encryption_keys

- name: Fetch encryption keys
  when: not ansible_check_mode
  run_once: true
  loop: "{{ encryption_keys.files | map(attribute='path') | list }}"
  fetch:
    flat: true
    src: "{{ item }}"
    dest: "{{ inventory_files_dir }}{{ o24_libellum_keys_base_path }}/clavem/"

- name: Delegate to localhost
  run_once: true
  delegate_to: localhost
  become: false
  block:
    - name: Check if old cert exists
      stat:
        path: "{{ inventory_files_dir }}{{ o24_libellum_certificates_base_path }}/clavem/encryption.crt.old"
      register: oldcert

    - name: Register saved certs
      find:
        paths: "{{ inventory_files_dir }}{{ tls_certificates_base_path }}/clavem"
        get_checksum: true
        patterns: "encryption*.crt"
      register: savedcerts

    - name: Compare saved certs to old cert
      loop: "{{ savedcerts.files | map(attribute='checksum') | list }}"
      when: oldcert.stat.checksum == item
      set_fact:
        movecert: false

    - name: Move Encryption Certificates
      when: oldcert.stat.exists and movecert
      vars:
        time: "{{ ansible_date_time.epoch }}"
      command:
        argv:
          - mv
          - "{{ inventory_files_dir }}{{ item.dir }}/clavem/encryption.{{ item.ext }}.old"
          - "{{ inventory_files_dir }}{{ item.dir }}/clavem/encryption_{{ time }}.{{ item.ext }}"
      loop:
        - { ext: "crt", dir: "{{ o24_libellum_certificates_base_path }}" }
        - { ext: "key", dir: "{{ o24_libellum_keys_base_path }}" }
        - { ext: "crt.csr", dir: "{{ o24_libellum_certificates_base_path }}" }

    - name: Ensure commit
      import_role:
        name: ensure_commit
      vars:
        ensure_commit:
          gitdir: "{{ inventory_files_dir }}"
          gitpaths: "{{ inventory_files_dir }}{{ o24_libellum_certificates_base_path }}/clavem {{ inventory_files_dir }}{{ o24_libellum_keys_base_path }}/clavem"
          gitprompt: "Make sure you've committed the certificate and key we just created"
          check: "{{ clavem.ensure_commit.check }}"
          fail: "{{ clavem.ensure_commit.fail }}"

- name: Copy encryption certificates
  when: not ansible_check_mode
  copy:
    src: "{{ inventory_files_dir }}{{ o24_libellum_certificates_base_path }}/clavem/"
    dest: "{{ o24_libellum_certificates_base_path }}/clavem/"
    owner: root
    group: clavem-server
    mode: 0640
  notify:
    - restart clavem-server

- name: Copy encryption keys
  when: not ansible_check_mode
  copy:
    src: "{{ inventory_files_dir }}{{ o24_libellum_keys_base_path }}/clavem/"
    dest: "{{ o24_libellum_keys_base_path }}/clavem/"
    owner: root
    group: clavem-server
    mode: 0640
  notify:
    - restart clavem-server

- name: Enable the server
  systemd:
    daemon_reload: true
    name: clavem-server
    enabled: true

- name: Open firewall for clavem service
  changed_when: "'Warning: ALREADY_ENABLED' not in firewallcmdout.stderr"
  register: firewallcmdout
  shell: |
    firewall-cmd {% if firewalld_zones is defined %} --zone={{ firewalld_zone[0].name }} {% endif %} --add-port=5044/tcp --permanent
    firewall-cmd {% if firewalld_zones is defined %} --zone={{ firewalld_zone[0].name }} {% endif %} --add-port=5044/tcp
